"""
build_notebook.py -- Customer Segmentation Analysis
------------------------------------------------------
Builds notebooks/customer_segmentation.ipynb by executing each code cell in
order (so the checked-in notebook already contains real outputs, tables, and
charts) and serializing to valid Jupyter nbformat v4 JSON -- no dependency
on jupyter/nbformat/nbconvert being installed.

Run from the project root:
    python scripts/build_notebook.py
"""

import ast
import base64
import io
import json
import os
import sys
import traceback
import contextlib

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_NOTEBOOKS_DIR = os.path.join(_PROJECT_ROOT, "notebooks")
os.makedirs(_NOTEBOOKS_DIR, exist_ok=True)
os.chdir(_NOTEBOOKS_DIR)

NOTEBOOK_PATH = "customer_segmentation.ipynb"

CELLS = []


def md(text):
    CELLS.append(("markdown", text))


def code(text):
    CELLS.append(("code", text))


# ===========================================================================
md(r"""# Customer Segmentation Analysis

**Goal:** group customers into statistically distinct, business-actionable
segments based on demographics and purchasing behavior (RFM: recency,
frequency, monetary value), then turn each segment into a targeted
marketing recommendation.

**Contents**
1. Load Data
2. Data Cleaning
3. Statistical Analysis & EDA
4. Feature Engineering & Scaling
5. Choosing K and Fitting K-Means
6. Cluster Visualization (PCA)
7. Segment Profiling
8. Business Recommendations

> **About the data:** `data/customer_data_raw.csv` is a synthetic dataset
> generated by `scripts/generate_data.py`, built from 5 underlying customer
> archetypes (so the clustering below has real, recoverable structure) with
> realistic messiness layered on top (duplicates, missing values,
> implausible ages, sign errors) for the cleaning section to address. Swap
> in your own customer export with the same columns to segment real data.
""")

# ===========================================================================
md("## 1. Load Data")
code("""\
import warnings
warnings.filterwarnings("ignore")

import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

sns.set_theme(style="whitegrid", palette="deep")
plt.rcParams["figure.dpi"] = 100
plt.rcParams["axes.titleweight"] = "bold"

ACCENT = "#2563EB"
PALETTE = ["#2563EB", "#F59E0B", "#10B981", "#EF4444", "#8B5CF6", "#06B6D4"]

df = pd.read_csv("../data/customer_data_raw.csv")
print(f"Raw dataset shape: {df.shape}")
df.head()
""")

code("""\
df.info()
""")

code("""\
print("Missing values per column:")
print(df.isna().sum()[df.isna().sum() > 0])
print(f"\\nDuplicate rows (excluding CustomerID): "
      f"{df.drop(columns=['CustomerID']).duplicated().sum()}")
print(f"\\nAge range: {df['Age'].min()} - {df['Age'].max()}  (implausible values expected here)")
print(f"Min AnnualIncome: {df['AnnualIncome'].min():,.2f}  (negative values expected here)")
""")

# ===========================================================================
md("""## 2. Data Cleaning

Steps:
- Standardize text columns (casing/whitespace)
- Drop duplicate customer rows
- Fix implausible ages (data entry errors, e.g. age=2 or age=145) by treating them as missing
- Fix sign errors in income (a few rows have negative income)
- Impute remaining missing values (median for numeric, mode for categorical)
""")

code("""\
raw_rows = len(df)

text_cols = ["Gender", "City", "MembershipTier", "PreferredChannel"]
for col in text_cols:
    df[col] = df[col].astype("string").str.strip()
df["MembershipTier"] = df["MembershipTier"].str.title()
df["PreferredChannel"] = df["PreferredChannel"].str.title()

dupes_removed = df.drop(columns=["CustomerID"]).duplicated().sum()
df = df.drop_duplicates(subset=[c for c in df.columns if c != "CustomerID"]).reset_index(drop=True)
df = df.drop_duplicates(subset="CustomerID").reset_index(drop=True)
print(f"Removed {dupes_removed} duplicate rows -> {df.shape}")
""")

code("""\
# Implausible ages (outside a believable adult customer range) -> treat as missing, then impute
invalid_age = ((df["Age"] < 16) | (df["Age"] > 95)).sum()
df.loc[(df["Age"] < 16) | (df["Age"] > 95), "Age"] = np.nan
print(f"Flagged {invalid_age} implausible ages as missing")

# Negative income is a sign error, not a real value -- take the absolute value
neg_income = (df["AnnualIncome"] < 0).sum()
df.loc[df["AnnualIncome"] < 0, "AnnualIncome"] = df.loc[df["AnnualIncome"] < 0, "AnnualIncome"].abs()
print(f"Fixed {neg_income} negative-income sign errors")
""")

code("""\
numeric_cols = ["Age", "AnnualIncome"]
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())
for col in ["Gender", "City", "MembershipTier"]:
    df[col] = df[col].fillna(df[col].mode().iloc[0])

clean_rows = len(df)
print(f"Remaining missing values: {int(df.isna().sum().sum())}")
print(f"Clean dataset: {clean_rows:,} rows (started from {raw_rows:,} raw rows)")
df.head()
""")

# ===========================================================================
md("## 3. Statistical Analysis & EDA")

md("### 3.1 Summary statistics")
code("""\
numeric_features = ["Age", "AnnualIncome", "TenureMonths", "RecencyDays", "Frequency",
                     "MonetaryTotal", "AvgBasketValue"]
df[numeric_features].describe().round(2)
""")

md("### 3.2 Feature distributions")
code("""\
fig, axes = plt.subplots(2, 3, figsize=(15, 8))
dist_cols = ["Age", "AnnualIncome", "RecencyDays", "Frequency", "MonetaryTotal", "AvgBasketValue"]
for ax, col in zip(axes.flat, dist_cols):
    sns.histplot(df[col], bins=30, color=ACCENT, ax=ax, kde=True)
    ax.set_title(col)
plt.tight_layout()
plt.show()
""")

md("### 3.3 Correlation between numeric features")
code("""\
fig, ax = plt.subplots(figsize=(8, 6.5))
corr = df[numeric_features].corr()
sns.heatmap(corr, annot=True, fmt=".2f", cmap="RdBu_r", center=0, ax=ax, square=True,
            cbar_kws={"shrink": 0.8})
ax.set_title("Correlation Between Customer Features")
plt.tight_layout()
plt.show()
""")

code("""\
income_corr = df[["AnnualIncome", "MonetaryTotal"]].corr().iloc[0, 1]
freq_corr = df[["Frequency", "MonetaryTotal"]].corr().iloc[0, 1]
print(f"Correlation(AnnualIncome, MonetaryTotal) = {income_corr:.2f}")
print(f"Correlation(Frequency, MonetaryTotal)     = {freq_corr:.2f}")
""")

md("### 3.4 Income by membership tier")
code("""\
fig, ax = plt.subplots(figsize=(8, 5))
order = ["Basic", "Silver", "Gold", "Platinum"]
sns.boxplot(data=df, x="MembershipTier", y="AnnualIncome", order=order, palette=PALETTE, ax=ax)
ax.set_title("Annual Income by Membership Tier")
plt.tight_layout()
plt.show()
""")

md("### 3.5 Frequency vs. monetary value, colored by recency")
code("""\
fig, ax = plt.subplots(figsize=(8, 6))
sc = ax.scatter(df["Frequency"], df["MonetaryTotal"], c=df["RecencyDays"], cmap="viridis_r", alpha=0.7, s=35)
plt.colorbar(sc, label="Recency (days since last purchase)")
ax.set_xlabel("Purchase Frequency")
ax.set_ylabel("Total Spend ($)")
ax.set_title("Purchase Frequency vs. Total Spend (colored by Recency)")
plt.tight_layout()
plt.show()
""")

# ===========================================================================
md("""## 4. Feature Engineering & Scaling

K-Means is distance-based, so features on very different scales (age in
years vs. income in tens of thousands of dollars) must be standardized
first, or high-magnitude features would dominate the distance calculation.
""")

code("""\
cluster_features = ["Age", "AnnualIncome", "TenureMonths", "RecencyDays",
                     "Frequency", "MonetaryTotal", "AvgBasketValue"]
X = df[cluster_features].copy()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(f"Scaled feature matrix shape: {X_scaled.shape}")
pd.DataFrame(X_scaled, columns=cluster_features).describe().round(2).loc[["mean", "std"]]
""")

# ===========================================================================
md("""## 5. Choosing K and Fitting K-Means

We evaluate K=2 through K=10 using two complementary methods:
- **Elbow method** (inertia): where adding more clusters stops meaningfully reducing within-cluster variance
- **Silhouette score**: how well-separated and internally consistent the clusters are (higher is better, max 1.0)
""")

code("""\
k_range = range(2, 11)
inertias, sil_scores = [], []
for k in k_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_scaled)
    inertias.append(km.inertia_)
    sil_scores.append(silhouette_score(X_scaled, labels))

fig, axes = plt.subplots(1, 2, figsize=(13, 5))
axes[0].plot(list(k_range), inertias, marker="o", color=ACCENT)
axes[0].set_title("Elbow Method (Inertia vs. K)")
axes[0].set_xlabel("Number of Clusters (K)"); axes[0].set_ylabel("Inertia")
axes[1].plot(list(k_range), sil_scores, marker="o", color=PALETTE[2])
axes[1].set_title("Silhouette Score vs. K")
axes[1].set_xlabel("Number of Clusters (K)"); axes[1].set_ylabel("Silhouette Score")
plt.tight_layout()
plt.show()

best_k = list(k_range)[int(np.argmax(sil_scores))]
print(f"Silhouette-optimal K = {best_k}")
print({k: round(s, 3) for k, s in zip(k_range, sil_scores)})
""")

md("""**K selection: statistical optimum vs. business interpretability.**

The silhouette score peaks at a low K, but inspecting those clusters shows
it merges behaviorally distinct groups (e.g. brand-new customers and
younger frequent shoppers) into one bucket -- too coarse to act on with a
marketing plan. We select **K=5** instead: still a solid silhouette score,
and it produces segments a marketing team can target independently. This
is a common, defensible trade-off in applied segmentation work.
""")

code("""\
K = 5
kmeans = KMeans(n_clusters=K, random_state=42, n_init=10)
df["Segment"] = kmeans.fit_predict(X_scaled)
final_silhouette = silhouette_score(X_scaled, df["Segment"])
print(f"Final model: K={K}, silhouette score={final_silhouette:.3f}")
df["Segment"].value_counts().sort_index()
""")

# ===========================================================================
md("## 6. Cluster Visualization (PCA)")
code("""\
pca = PCA(n_components=2, random_state=42)
pcs = pca.fit_transform(X_scaled)
df["PC1"], df["PC2"] = pcs[:, 0], pcs[:, 1]
explained_var = pca.explained_variance_ratio_
print(f"PC1 explains {explained_var[0]*100:.1f}% of variance, PC2 explains {explained_var[1]*100:.1f}%")

fig, ax = plt.subplots(figsize=(9, 7))
for seg in sorted(df["Segment"].unique()):
    sub = df[df["Segment"] == seg]
    ax.scatter(sub["PC1"], sub["PC2"], label=f"Segment {seg}", alpha=0.7, s=35,
               color=PALETTE[seg % len(PALETTE)])
ax.set_xlabel(f"PC1 ({explained_var[0]*100:.1f}% variance)")
ax.set_ylabel(f"PC2 ({explained_var[1]*100:.1f}% variance)")
ax.set_title(f"Customer Segments in PCA Space (K={K})")
ax.legend()
plt.tight_layout()
plt.show()
""")

# ===========================================================================
md("## 7. Segment Profiling")
code("""\
profile = df.groupby("Segment")[cluster_features].mean().round(1)
profile["CustomerCount"] = df.groupby("Segment").size()
profile["PctOfCustomers"] = (profile["CustomerCount"] / len(df) * 100).round(1)
profile
""")

code("""\
def name_segment(row, overall):
    if row["MonetaryTotal"] > overall["MonetaryTotal"] * 1.4 and row["Frequency"] > overall["Frequency"]:
        return "High-Value Loyalists"
    if row["MonetaryTotal"] > overall["MonetaryTotal"] * 1.1 and row["Frequency"] < overall["Frequency"]:
        return "Occasional Big Spenders"
    if row["RecencyDays"] > overall["RecencyDays"] * 1.3 and row["Frequency"] < overall["Frequency"]:
        return "New / Low-Engagement"
    if row["Age"] < overall["Age"] * 0.75:
        return "Young Digital Shoppers"
    return "Budget Shoppers"

overall_means = df[cluster_features].mean()
profile["SegmentName"] = profile.apply(lambda r: name_segment(r, overall_means), axis=1)

seen = {}
final_names = []
for name in profile["SegmentName"]:
    seen[name] = seen.get(name, 0) + 1
    final_names.append(name if seen[name] == 1 else f"{name} ({seen[name]})")
profile["SegmentName"] = final_names

segment_id_to_name = profile["SegmentName"].to_dict()
df["SegmentName"] = df["Segment"].map(segment_id_to_name)
profile[["SegmentName", "CustomerCount", "PctOfCustomers"] + cluster_features]
""")

md("### Segment sizes")
code("""\
fig, ax = plt.subplots(figsize=(9, 5))
counts = df["SegmentName"].value_counts()
ax.bar(counts.index, counts.values, color=PALETTE[:len(counts)])
ax.set_title("Customer Count by Segment")
ax.set_ylabel("Number of Customers")
plt.xticks(rotation=25, ha="right")
plt.tight_layout()
plt.show()
""")

md("### Segment profile comparison (normalized)")
code("""\
norm_profile = (profile[cluster_features] - profile[cluster_features].min()) / (
    profile[cluster_features].max() - profile[cluster_features].min() + 1e-9
)
fig, ax = plt.subplots(figsize=(11, 6))
x = np.arange(len(cluster_features))
width = 0.8 / len(profile)
for i, (seg_id, row) in enumerate(norm_profile.iterrows()):
    ax.bar(x + i * width, row.values, width=width, label=segment_id_to_name[seg_id],
           color=PALETTE[i % len(PALETTE)])
ax.set_xticks(x + width * (len(profile) - 1) / 2)
ax.set_xticklabels(cluster_features, rotation=20, ha="right")
ax.set_title("Segment Profiles (Normalized 0-1 per Feature)")
ax.legend(bbox_to_anchor=(1.02, 1), loc="upper left", fontsize=8)
plt.tight_layout()
plt.show()
""")

# ===========================================================================
md("""## 8. Business Recommendations

Translating each segment's profile into a targeted marketing action.
""")

code("""\
sorted_segs = profile.sort_values("MonetaryTotal", ascending=False)
top_seg_id = sorted_segs.index[0]
top_seg_name = segment_id_to_name[top_seg_id]

low_engagement_candidates = profile.sort_values("RecencyDays", ascending=False)
churn_risk_id = low_engagement_candidates.index[0]
churn_risk_name = segment_id_to_name[churn_risk_id]

recommendations = {
    "High-Value Loyalists": "Reward with loyalty perks, early access to new products, and premium-tier "
                              "upsell offers. They already buy often and recently -- the goal is retention, not discounts.",
    "Occasional Big Spenders": "Re-engage with personalized, higher-AOV bundle offers timed around their "
                                 "typical (infrequent) purchase cycle rather than high-frequency promotions.",
    "New / Low-Engagement": "Focus on onboarding: low-friction second-purchase incentives, guided product "
                              "recommendations, and a welcome series to build the purchase habit before they churn.",
    "Young Digital Shoppers": "Meet them on mobile/social channels with frequent, lower-AOV promotions, "
                                "referral incentives, and app-exclusive perks.",
    "Budget Shoppers": "Emphasize value messaging (bundles, loyalty points, price-match guarantees) -- "
                         "this group is price-sensitive but reasonably frequent, so small frictionless "
                         "incentives can lift order size.",
}

for seg_id in profile.index:
    name = segment_id_to_name[seg_id]
    base_name = name.split(" (")[0]
    print(f"[{name}] ({int(profile.loc[seg_id, 'CustomerCount'])} customers, "
          f"{profile.loc[seg_id, 'PctOfCustomers']:.1f}% of base)")
    print(f"  -> {recommendations.get(base_name, 'Tailor offers based on this segment profile.')}\\n")
""")

code("""\
insights = [
    f"K-Means clustering was evaluated for K=2 through K=10 using the elbow method and silhouette score. "
    f"The purely statistical optimum was K={best_k}, but it merged behaviorally distinct groups together. "
    f"K={K} was selected instead (silhouette score {final_silhouette:.2f}) to produce segments the "
    f"marketing team can act on independently.",

    f"'{top_seg_name}' is the highest-value segment, averaging ${sorted_segs.loc[top_seg_id, 'MonetaryTotal']:,.0f} "
    f"in total spend ({sorted_segs.loc[top_seg_id, 'PctOfCustomers']:.1f}% of the customer base) and should be "
    f"prioritized for loyalty and retention investment.",

    f"'{churn_risk_name}' has the highest average recency ({profile.loc[churn_risk_id, 'RecencyDays']:.0f} days "
    f"since last purchase), signaling elevated churn risk and a need for a targeted win-back campaign.",

    f"Annual income and total spend correlate at r={income_corr:.2f}, while purchase frequency and total "
    f"spend correlate at r={freq_corr:.2f} -- behavioral data (frequency, recency) is a stronger driver of "
    f"customer value than income alone, and should be weighted accordingly in targeting decisions.",

    "Segment-specific marketing is recommended over one-size-fits-all campaigns: high-value segments respond "
    "to loyalty/exclusivity messaging, while low-engagement/new segments respond better to onboarding "
    "incentives and low-friction first/second-purchase offers.",
]
for i, line in enumerate(insights, 1):
    print(f"{i}. {line}\\n")
""")

md("""## 9. Export for the Dashboard

Saves the cleaned + segmented dataset and summary so `dashboard/app.py` can
consume them without re-running this notebook.
""")

code("""\
import os
os.makedirs("../outputs", exist_ok=True)
df.to_csv("../outputs/customers_with_segments.csv", index=False)

summary = {
    "k_selected": int(K),
    "silhouette_optimal_k": int(best_k),
    "silhouette_score": round(float(final_silhouette), 3),
    "pca_explained_variance_pct": [round(float(v) * 100, 1) for v in explained_var],
    "segments": {
        segment_id_to_name[seg_id]: {
            "customer_count": int(row["CustomerCount"]),
            "pct_of_customers": float(row["PctOfCustomers"]),
            "avg_age": float(row["Age"]),
            "avg_annual_income": float(row["AnnualIncome"]),
            "avg_tenure_months": float(row["TenureMonths"]),
            "avg_recency_days": float(row["RecencyDays"]),
            "avg_frequency": float(row["Frequency"]),
            "avg_monetary_total": float(row["MonetaryTotal"]),
            "avg_basket_value": float(row["AvgBasketValue"]),
        }
        for seg_id, row in profile.iterrows()
    },
}
with open("../outputs/segment_summary.json", "w") as f:
    json.dump(summary, f, indent=2)
with open("../outputs/insights.json", "w") as f:
    json.dump(insights, f, indent=2)

print("Saved: outputs/customers_with_segments.csv, outputs/segment_summary.json, outputs/insights.json")
print("\\nNext step: launch the dashboard with `streamlit run dashboard/app.py` from the project root.")
""")

# ===========================================================================
# Execute all cells (same machinery as Task 1's notebook builder)
# ===========================================================================

def run_all():
    namespace = {}
    nb_cells = []
    exec_count = 0

    for cell_type, content in CELLS:
        if cell_type == "markdown":
            nb_cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": content.splitlines(keepends=True),
            })
            continue

        exec_count += 1
        outputs = []
        buf = io.StringIO()
        source = content.rstrip("\n")

        body_src, expr_src = source, None
        try:
            tree = ast.parse(source)
            if tree.body and isinstance(tree.body[-1], ast.Expr):
                last_node = tree.body[-1]
                lines = source.split("\n")
                expr_src = "\n".join(lines[last_node.lineno - 1: last_node.end_lineno])
                remaining_lines = lines[: last_node.lineno - 1]
                body_src = "\n".join(remaining_lines)
        except SyntaxError:
            pass

        result = None
        try:
            with contextlib.redirect_stdout(buf):
                if body_src.strip():
                    exec(compile(body_src, "<cell>", "exec"), namespace)
                if expr_src:
                    result = eval(compile(expr_src, "<cell>", "eval"), namespace)
        except Exception:
            err_text = traceback.format_exc()
            outputs.append({
                "output_type": "error",
                "ename": "Error",
                "evalue": "See traceback",
                "traceback": err_text.splitlines(),
            })
            print(f"ERROR in cell {exec_count}:\n{err_text}", file=sys.stderr)

        stdout_text = buf.getvalue()
        if stdout_text:
            outputs.append({
                "output_type": "stream",
                "name": "stdout",
                "text": stdout_text.splitlines(keepends=True),
            })

        fig_nums = plt.get_fignums()
        for fig_num in fig_nums:
            fig = plt.figure(fig_num)
            img_buf = io.BytesIO()
            fig.savefig(img_buf, format="png", bbox_inches="tight", dpi=100)
            img_b64 = base64.b64encode(img_buf.getvalue()).decode("ascii")
            outputs.append({
                "output_type": "display_data",
                "data": {"image/png": img_b64, "text/plain": ["<Figure>"]},
                "metadata": {"image/png": {"width": 700}},
            })
            plt.close(fig)

        if result is not None:
            if isinstance(result, pd.DataFrame):
                outputs.append({
                    "output_type": "execute_result",
                    "execution_count": exec_count,
                    "data": {
                        "text/html": result.to_html(max_rows=20).splitlines(keepends=True),
                        "text/plain": repr(result).splitlines(keepends=True),
                    },
                    "metadata": {},
                })
            else:
                outputs.append({
                    "output_type": "execute_result",
                    "execution_count": exec_count,
                    "data": {"text/plain": repr(result).splitlines(keepends=True)},
                    "metadata": {},
                })

        nb_cells.append({
            "cell_type": "code",
            "execution_count": exec_count,
            "metadata": {},
            "outputs": outputs,
            "source": content.splitlines(keepends=True),
        })

    return nb_cells


if __name__ == "__main__":
    cells = run_all()
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {
                "name": "python", "version": "3.11", "mimetype": "text/x-python",
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py", "pygments_lexer": "ipython3",
                "nbconvert_exporter": "python",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    with open(NOTEBOOK_PATH, "w") as f:
        json.dump(notebook, f, indent=1)
    print(f"\nWrote {NOTEBOOK_PATH} with {len(cells)} cells.")
